language: ruby
rvm:
  - 2.3.3
before_install:
  - openssl aes-256-cbc -K $encrypted_4a3dca1ebbca_key -iv $encrypted_4a3dca1ebbca_iv -in howdo_rsa.enc -out howdo_rsa -d
script:
  - git config --global user.name 'Autocommit'
  - git config --global user.email 'bot@howdo.com'
  - git remote set-url origin git@github.com:howdocom/howdo-slate.git
  - ./deploy.sh
branches:
  only:
  - master
env:
  - GIT_SSH_COMMAND='ssh -i howdo_rsa'